# Generated by Django 5.0.1 on 2024-01-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='image',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.FileField(null=True, upload_to='static/img/'),
        ),
    ]
