# Generated by Django 5.0.1 on 2024-01-26 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0002_remove_publicacion_image_publicacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
