# Generated by Django 5.0.1 on 2024-01-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0003_publicacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
